### ISSUE TITLE
Kotlin sourceset is not recognised

### ISSUE THREAD

**Issue by kikugie** [SHsuperCM/Stonecutter#2]
In a mod's `build.gradle` (for example https://github.com/mineblock11/example-stonecutter-project) add
```gradle
plugins {
    id "org.jetbrains.kotlin.jvm" version "1.9.20"
}
```
After reloading gradle, IDEA doesn't recognize `src/main/kotlin` as a sourceset and doesn't compile it.  
Same result with adding kotlin in `settings.gradle` and later applying in `build.gradle`.

**Comment by SHsuperCM** [comment]
https://github.com/SHsuperCM/Stonecutter/blob/d39c7fbefbb2774cfbc4613d027d7920a0344571/src/main/java/io/shcm/shsupercm/fabric/stonecutter/StonecutterBuildGradle.java#L56-L57
https://github.com/SHsuperCM/Stonecutter/blob/d39c7fbefbb2774cfbc4613d027d7920a0344571/src/main/java/io/shcm/shsupercm/fabric/stonecutter/StonecutterBuildGradle.java#L64-L65

 

`org.gradle.api.tasks.SourceSet` only had Java and Resources iirc. 

I'mma be honest.. it'd be a miracle if it worked on kotlin even if it set the sourceset correctly. And I am definitely not looking to support kotlin tho 😅 everything about it is cursed af and the maintenance is not something I'm looking to do.

Ofc, if you or anyone is interested, feel free to fork. but this is not going to be officially supported as far as I can tell.
